version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: recipe-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recipe_db
      MYSQL_USER: recipe_user
      MYSQL_PASSWORD: recipe_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - recipe-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  # Recipe Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: recipe-app
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=database-1.cjckackqgiiz.ap-southeast-1.rds.amazonaws.com
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=admin
      - MYSQL_PASSWORD=mana-givery
      - MYSQL_DATABASE=mana
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - recipe-network
    healthcheck:
      test: ['CMD', 'node', '--eval', "fetch('http://localhost:8080').then(() => process.exit(0)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development Service (optional)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: recipe-app-dev
    restart: unless-stopped
    ports:
      - '8081:8080'
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=database-1.cjckackqgiiz.ap-southeast-1.rds.amazonaws.com
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=admin
      - MYSQL_PASSWORD=mana-givery
      - MYSQL_DATABASE=mana
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - recipe-network
    profiles:
      - development

volumes:
  mysql_data:

networks:
  recipe-network:
    driver: bridge
